"""Regenerate the scenario figures in docs/scenarios.md.

    python docs/figures/make_scenario_figures.py        # numpy only

Every figure here is drawn from verbatim CLI output committed under data/, regenerated by
data/make_data.sh. Nothing is typed in from memory and nothing is redrawn by hand: if a figure
says the decay heat crosses a kilowatt at 305 days, that number came out of `nusift when`.

The split from make_figures.py is by PURPOSE rather than by machinery. That file illustrates the
METHOD -- what an interval integral is, how a subtraction loses its digits, what the air
coefficients do -- and its figures belong beside the equations. These illustrate the CAPABILITIES:
one per subcommand, each showing what the command is for on a source it actually suits. Both draw
through svgplot.py, so the two sets cannot drift into different visual languages.

The chart primitives at the top are shared by most of the nineteen figures, because nineteen
bespoke plotting functions would be nineteen chances for two bar charts to disagree about where
their labels go.
"""

from __future__ import annotations

import csv
import math
from pathlib import Path

from svgplot import Axes, circle, line, polyline, rect, svg, text

OUT = Path(__file__).resolve().parent
DATA = OUT / "data"

# Decade ticks and their spellings, used by every log-time axis here so that two figures over
# the same window cannot label it differently.
DECADES = [
    (1.0, "1 s"), (60.0, "1 m"), (3600.0, "1 h"), (86400.0, "1 d"), (864000.0, "10 d"),
    (3.15576e7, "1 y"), (3.15576e8, "10 y"), (3.15576e9, "100 y"), (3.15576e10, "1 ky"),
]


def read_csv(name):
    with (DATA / name).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def number(row, field, default=0.0):
    """A CSV cell as a float, with an EMPTY cell meaning absent rather than zero.

    The reports write an empty field where a quantity was not stated -- no evaluated sigma, no
    end time on an instantaneous row -- precisely so that "none stated" and "stated as zero"
    stay distinguishable. Reading them back has to preserve that or the figures would quietly
    assert the thing the format went to trouble to avoid.
    """
    raw = (row.get(field) or "").strip()
    return float(raw) if raw else default


def read_text(name):
    return (DATA / name).read_text(encoding="utf-8")


def si(value, digits=3):
    """A number as a report would print it: three significant figures, exponent when needed."""
    if value == 0:
        return "0"
    exponent = math.floor(math.log10(abs(value)))
    if -3 <= exponent < 5:
        return f"{value:,.{max(0, digits - 1 - exponent)}f}".rstrip("0").rstrip(".")
    mantissa = value / 10.0**exponent
    return f"{mantissa:.2f}e{exponent}"


def duration(seconds):
    """Seconds as the CLI spells them, so a figure and a report agree about when something is."""
    for size, unit in ((3.15576e7, "y"), (86400.0, "d"), (3600.0, "h"), (60.0, "m")):
        if seconds >= size:
            return f"{seconds / size:.3g} {unit}"
    return f"{seconds:.3g} s"


def time_axis(ax, lo, hi):
    keep = [(v, l) for v, l in DECADES if lo <= v <= hi]
    return ax.vgrid([v for v, _ in keep], [l for _, l in keep])


def header(parts, ax, title, subtitle=None):
    parts.append(text(ax.left, 26, title, "ink", 13, "start", "600"))
    if subtitle:
        parts.append(text(ax.left, 44, subtitle, "muted", 11.5))


def notes(parts, ax, lines, top=None, width=11.5):
    """Caption lines under a figure. Returns the y of the last one, so a caller can size the SVG
    to its text rather than guessing a height that clips on one machine and not another."""
    y = (ax.bottom + 46) if top is None else top
    for i, entry in enumerate(lines):
        parts.append(text(ax.left, y + i * 18, entry, "ink" if i == 0 else "muted", 12 if i == 0 else width))
    return y + max(0, len(lines) - 1) * 18


def write(path, width, height, parts, title):
    path.write_text(svg(width, height, "\n".join(parts), title), encoding="utf-8")


# --------------------------------------------------------------------------------------
# Primitive -- a ranked horizontal bar chart, which is what most of these commands print.
# --------------------------------------------------------------------------------------

def ranked_bars(parts, left, top, width, rows, value_of, label_of, note_of=None, cls_of=None,
                row_h=22, bar_h=13, label_w=76, value_w=96):
    """Rows in the order given, longest bar normalized to the widest available space.

    Deliberately NOT sorted here: every one of these commands has already chosen an order, and
    that order is usually the point -- a shortlist's build order is not a ranking, and a variance
    fraction is not a share of the answer.
    """
    values = [abs(value_of(r)) for r in rows]
    span = max(values) if values else 1.0
    bar_left = left + label_w
    bar_max = width - label_w - value_w
    for i, row in enumerate(rows):
        y = top + i * row_h
        value = abs(value_of(row))
        cls = cls_of(i, row) if cls_of else f"t{i % 8}"
        parts.append(text(left, y + bar_h - 2, label_of(row), "ink", 11, "start", "500"))
        length = bar_max * (value / span) if span > 0 else 0.0
        parts.append(rect(bar_left, y, max(length, 0.6), bar_h, cls, 0.75, rx=1.5, width=0))
        parts.append(text(bar_left + bar_max + 8, y + bar_h - 2,
                          note_of(row) if note_of else si(value), "muted", 10.5))
    return top + len(rows) * row_h


def _pixel_curve(ax, points):
    """A series as pixel coordinates, ascending in x, for label placement to reason over."""
    return sorted(((ax.x(t), ax.y(v)) for t, v in points), key=lambda p: p[0])


def _at(curve, px):
    """Linear interpolation of a pixel curve at a pixel x, or None outside its range."""
    if px < curve[0][0] or px > curve[-1][0]:
        return None
    for (x0, y0), (x1, y1) in zip(curve, curve[1:]):
        if x0 <= px <= x1:
            if x1 == x0:
                return y0
            return y0 + (y1 - y0) * (px - x0) / (x1 - x0)
    return curve[-1][1]


def place_labels(ax, series, min_gap=14.0, min_dx=48.0, margin=34.0, candidates=41):
    """Anchor each curve's label where that curve is furthest from every other one.

    Labeling each curve at its own maximum is the obvious rule and it fails badly on a decay
    plot: the curves that start highest all peak at the first sample, so every label lands in the
    same corner on top of the others. What makes a label readable is not that its curve is high
    there but that no OTHER curve is near it there, which is what this maximizes.

    Labels are then placed one at a time, and each takes the best position that does not collide
    with one already placed. Moving a label ALONG its own curve is preferred to nudging it off,
    because a label that has been pushed clear of the traffic is also a label that no longer sits
    on the line it names -- which is a worse failure than the crowding it was fixing.
    """
    curves = [_pixel_curve(ax, points) for _, points in series]
    lo, hi = ax.left + margin, ax.right - margin
    xs = [lo + i * (hi - lo) / (candidates - 1) for i in range(candidates)]

    # Each curve's candidate anchors, best separation first.
    options = []
    for i, curve in enumerate(curves):
        scored = []
        for px in xs:
            y = _at(curve, px)
            if y is None:
                continue
            others = [_at(other, px) for j, other in enumerate(curves) if j != i]
            gap = min((abs(y - o) for o in others if o is not None), default=1e6)
            scored.append((gap, px, y))
        scored.sort(key=lambda z: (-z[0], z[1]))
        options.append(scored or [(0.0, curve[len(curve) // 2][0], curve[len(curve) // 2][1])])

    # Most constrained first: a curve whose best option is already cramped has the least room to
    # give up, so it chooses before the ones that can sit almost anywhere.
    order = sorted(range(len(curves)), key=lambda i: options[i][0][0])
    placed = [None] * len(curves)
    for i in order:
        chosen = None
        for gap, px, py in options[i]:
            if all(abs(px - q[0]) >= min_dx or abs(py - q[1]) >= min_gap
                   for q in placed if q is not None):
                chosen = (px, py)
                break
        if chosen is None:
            # Nothing on this curve is clear of everything already placed, so take its best
            # anchor and lift the label until it is. Rare, and better than dropping the label.
            _, px, py = options[i][0]
            while any(abs(px - q[0]) < min_dx and abs(py - q[1]) < min_gap
                      for q in placed if q is not None):
                py -= min_gap
            chosen = (px, py)
        placed[i] = chosen
    return placed


def series_plot(parts, ax, series, label_at="spread", dash=None):
    """One line per named series, each labeled on the curve rather than in a legend box."""
    anchors = place_labels(ax, series) if label_at == "spread" else None
    for i, (name, points) in enumerate(series):
        cls = f"s{i % 8}"
        parts.append(ax.path([p[0] for p in points], [p[1] for p in points], cls, 1.9, dash))
        if anchors is not None:
            px, py = anchors[i]
        elif label_at == "max":
            bx, by = max(points, key=lambda p: p[1])
            px, py = ax.x(bx), ax.y(by)
        else:
            px, py = ax.x(points[-1][0]), ax.y(points[-1][1])
        parts.append(text(px, py - 7, name, f"t{i % 8}", 10, "middle", "600"))


# ======================================================================================
# Track 0 -- knowing what you have
# ======================================================================================

def figure_store(path):
    """What the evaluation can and cannot answer, from `nusift data info`."""
    info = read_text("scenario-store-info.txt")

    def number(pattern, default=0):
        import re
        match = re.search(pattern, info)
        return int(match.group(1).replace(",", "")) if match else default

    staged = number(r"nuclides staged:\s+(\d+)")
    chain = number(r"chain size:\s+(\d+)")
    unstable = number(r"unstable nuclides:\s+(\d+)")
    with_lines = number(r"with discrete photon lines:\s+(\d+)")
    no_lines = number(r"(\d+) unstable nuclides have an evaluated average photon energy but no discrete")
    sf_no_yields = number(r"SF branch, no yields staged:\s+(\d+)")

    bars = [
        ("staged from tapes", staged, "every nuclide the evaluation carries a record for"),
        ("chain, after closure", chain, "plus daughters and fission products with nowhere else to land"),
        ("unstable", unstable, "the ones with a decay constant at all"),
        ("with photon lines", with_lines, "the only ones an exposure answer can come from"),
    ]

    w = 880
    left, top = 74, 96
    parts = []
    parts.append(text(left, 26, "What this store can answer, and for how much of itself", "ink", 13, "start", "600"))
    parts.append(text(left, 44, "ENDF/B-VIII.1 as staged — `nusift data info`", "muted", 11.5))

    span = max(v for _, v, _ in bars)
    for i, (label, value, why) in enumerate(bars):
        y = top + i * 44
        parts.append(text(left, y + 12, label, "ink", 11.5, "start", "500"))
        parts.append(rect(left + 150, y, (w - 300) * value / span, 15, f"t{i % 8}", 0.75, rx=2, width=0))
        parts.append(text(left + 150 + (w - 300) * value / span + 8, y + 12, f"{value:,}", "ink", 11, "start", "600"))
        parts.append(text(left + 150, y + 29, why, "muted", 10.5))

    y = top + len(bars) * 44 + 14
    parts.append(text(left, y, f"{no_lines:,} unstable nuclides have an evaluated average photon energy and no discrete lines to spend it on.", "ink", 12))
    parts.append(text(left, y + 18, "That is not a defect to work around — it is the figure that decides whether an exposure answer means anything,", "muted", 11.5))
    parts.append(text(left, y + 34, "and it is why a store with no lines refuses the question rather than returning zeros.", "muted", 11.5))
    parts.append(text(left, y + 56, f"{sf_no_yields} nuclides have a spontaneous-fission branch and no yield set at any energy: their fission products", "muted", 11.5))
    parts.append(text(left, y + 72, "go nowhere, which the store reports rather than silently dropping.", "muted", 11.5))

    write(path, w, y + 92, parts, "Store coverage: what the evaluation can be asked")
    print(f"  store: {staged} staged, {chain} in chain, {with_lines} with lines")


def figure_decay(path):
    """Raw trajectories: the ingrowth a ranking would hide behind its ordering."""
    rows = read_csv("scenario-decay.csv")
    header_row = list(rows[0].keys())
    times = [float(t) for t in header_row[1:]]

    wanted = ["I-131", "Ba-140", "La-140", "Zr-95", "Cs-137", "Sr-90"]
    series = []
    for name in wanted:
        for row in rows:
            if row["nuclide"] == name:
                values = [float(row[t]) for t in header_row[1:]]
                series.append((name, [(t, v) for t, v in zip(times, values) if v > 0]))
                break

    lo = min(min(v for _, v in pts) for _, pts in series)
    hi = max(max(v for _, v in pts) for _, pts in series)
    w, h = 880, 500
    ax = Axes(84, 800, 86, 330, (times[0], times[-1]), (max(lo, hi * 1e-9), hi * 3), xlog=True, ylog=True)

    parts = []
    exponent_hi = int(math.floor(math.log10(hi * 3)))
    grid = [10.0**e for e in range(exponent_hi - 8, exponent_hi + 1, 2)]
    parts += ax.hgrid(grid, [f"1e{int(math.log10(g))}" for g in grid])
    parts += time_axis(ax, times[0], times[-1])
    series_plot(parts, ax, series)
    parts += ax.frame()

    header(parts, ax, "Atoms against time — 20 kt U-235 thermal fission",
           "`nusift decay` — the trajectories themselves, before any weight is applied")
    parts.append(text(ax.right, ax.bottom + 34, "time after fission →", "muted", 11, "end"))
    notes(parts, ax, [
        "La-140 is not seeded and still peaks near a day: it is grown in by Ba-140, and a curve that only ever falls would be the",
        "signature of a chain that was not solved. This is the one command that applies no weight at all — every other figure here is",
        "this matrix multiplied by something, which is why they can disagree about what matters without disagreeing about the physics.",
    ])
    write(path, w, h, parts, "Nuclide trajectories after fission")
    print(f"  decay: {len(series)} trajectories over {len(times)} samples")


def figure_nuclide(path):
    """A nuclide is a key, and an isomer is a different one."""
    lines = [l for l in read_text("scenario-nuclide.txt").splitlines() if l.strip()]
    typed = ["Cs-137", "ba137m", "TC-99M", "u235", "Co60", "Ba-137"]

    rows = []
    for spelling, line in zip(typed, lines):
        parts_ = line.split()
        rows.append((spelling, parts_[0], parts_[-1].split("=")[1]))

    w = 880
    left, top = 74, 100
    parts = []
    parts.append(text(left, 26, "A nuclide is one integer, and an isomer is a different one", "ink", 13, "start", "600"))
    parts.append(text(left, 44, "`nusift nuclide` — what the canonicalizer accepts, and what it refuses to blur", "muted", 11.5))
    parts.append(text(left, 82, "as typed", "muted", 10.5, "start", "600"))
    parts.append(text(left + 190, 82, "canonical", "muted", 10.5, "start", "600"))
    parts.append(text(left + 350, 82, "key  Z·10000 + A·10 + I", "muted", 10.5, "start", "600"))

    for i, (spelling, canonical, key) in enumerate(rows):
        y = top + i * 26
        isomer = canonical.endswith("m")
        parts.append(text(left, y + 11, spelling, "muted", 11.5))
        parts.append(text(left + 190, y + 11, canonical, "warn" if isomer else "ink", 11.5, "start", "600"))
        parts.append(text(left + 350, y + 11, key, "warn" if isomer else "ink", 11.5))

    y = top + len(rows) * 26 + 22
    parts.append(text(left, y, "Ba-137 and Ba-137m differ by one in the last digit and by everything else that matters.", "ink", 12))
    parts.append(text(left, y + 20, "One is stable and the other has a 153-second half-life and carries the 662 keV line that the whole cesium dose story rests on.", "muted", 11.5))
    parts.append(text(left, y + 36, "So spelling is forgiving and identity is not: case, separators and ordering are all accepted, and an isomer is never merged", "muted", 11.5))
    parts.append(text(left, y + 52, "into its ground state to make a name resolve.", "muted", 11.5))
    parts.append(text(left, y + 74, "The key is the same integer in the HDF5 store, the chain index, the inventory and every CSV column — sortable, and stable", "muted", 11.5))
    parts.append(text(left, y + 90, "across every layer, so no two parts of the tool can disagree about which nuclide they are discussing.", "muted", 11.5))
    write(path, w, y + 110, parts, "Nuclide naming and the ZAI key")
    print(f"  nuclide: {len(rows)} spellings canonicalized")


def figure_inventory(path):
    """The same object in becquerel and in atoms, which are not proportional."""
    source = {}
    for line in (Path(__file__).resolve().parents[2] / "examples" / "contaminated_component.csv").read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("nuclide"):
            continue
        name, quantity, unit = [c.strip() for c in line.split(",")[:3]]
        source[name] = float(quantity)

    atoms = {}
    for line in read_text("scenario-inventory-atoms.csv").splitlines():
        if line.startswith("#") or line.startswith("nuclide") or not line.strip():
            continue
        name, quantity, _ = [c.strip() for c in line.split(",")[:3]]
        atoms[name] = float(quantity)

    rows = [(n, source[n], atoms[n]) for n in source if n in atoms]
    rows.sort(key=lambda r: -r[1])

    w = 900
    left, top = 74, 106
    bar_w = 300
    parts = []
    parts.append(text(left, 26, "One object, two ways of writing it down", "ink", 13, "start", "600"))
    parts.append(text(left, 44, "`nusift inventory convert --units atoms` — examples/contaminated_component.csv", "muted", 11.5))
    parts.append(text(left + 110 + bar_w / 2, 84, "as reported  (Bq)", "muted", 10.5, "middle", "600"))
    parts.append(text(left + 110 + bar_w + 60 + bar_w / 2, 84, "as the engine needs it  (atoms)", "muted", 10.5, "middle", "600"))

    def logspan(values):
        lo, hi = math.log10(min(values)), math.log10(max(values))
        return lo - 0.4, hi

    bq_lo, bq_hi = logspan([r[1] for r in rows])
    at_lo, at_hi = logspan([r[2] for r in rows])

    for i, (name, bq, at) in enumerate(rows):
        y = top + i * 24
        parts.append(text(left, y + 11, name, "ink", 11, "start", "500"))
        b = bar_w * (math.log10(bq) - bq_lo) / (bq_hi - bq_lo)
        a = bar_w * (math.log10(at) - at_lo) / (at_hi - at_lo)
        parts.append(rect(left + 110, y, max(b, 1.0), 13, "fill-a", 0.75, rx=1.5, width=0))
        parts.append(rect(left + 110 + bar_w + 60, y, max(a, 1.0), 13, "fill-b", 0.75, rx=1.5, width=0))
        parts.append(text(left + 110 + bar_w + 6, y + 11, si(bq), "muted", 9.5))
        parts.append(text(left + 110 + bar_w + 60 + max(a, 1.0) + 6, y + 11, si(at), "muted", 9.5))

    y = top + len(rows) * 24 + 24
    parts.append(text(left, y, "Cs-137 and Ba-137m are within a few percent of each other in becquerel and seven orders of magnitude apart in atoms.", "ink", 12))
    parts.append(text(left, y + 20, "A becquerel is a RATE and an atom count is an amount, and what separates them is the decay constant: Ba-137m lives 153 seconds", "muted", 11.5))
    parts.append(text(left, y + 36, "and Cs-137 thirty years, so it takes seven orders of magnitude fewer of the one to decay just as often.", "muted", 11.5))
    parts.append(text(left, y + 58, "Both bars are LOG scaled, which is the only way to show them together — and is itself the point.", "muted", 11.5))
    parts.append(text(left, y + 80, "The engine works in atoms because that is what the decay matrix acts on. Every input unit is converted once, on the way in,", "muted", 11.5))
    parts.append(text(left, y + 96, "which is why an activity input needs a half-life from the store and a gram input needs a molar mass — and why a store that", "muted", 11.5))
    parts.append(text(left, y + 112, "carries no atomic weights refuses gram input rather than guessing A for the molar mass.", "muted", 11.5))
    write(path, w, y + 132, parts, "The same inventory in becquerel and in atoms")
    print(f"  inventory: {len(rows)} rows converted")


# ======================================================================================
# Track 1 -- the source term
# ======================================================================================

def figure_rank_two_metrics(path):
    """The same source at the same instant, ranked by two things it can be worth."""
    activity = read_csv("scenario-rank-activity.csv")[:8]
    heat = read_csv("scenario-rank-heat.csv")[:8]

    w = 900
    parts = []
    parts.append(text(66, 26, "One source, one instant, two questions", "ink", 13, "start", "600"))
    parts.append(text(66, 44, "20 kt U-235 thermal fission at 1 day — `nusift rank --metric activity` and `--metric heat`", "muted", 11.5))

    for column, (title, rows, unit) in enumerate(
            [("by activity  (Bq)", activity, "Bq"), ("by decay heat  (W)", heat, "W")]):
        left = 66 + column * 452
        parts.append(text(left, 84, title, "ink", 11.5, "start", "600"))
        ranked_bars(parts, left, 100, 400, rows,
                    value_of=lambda r: float(r["value"]),
                    label_of=lambda r: r["contributor"],
                    note_of=lambda r: f"{float(r['fraction']) * 100:.1f}%",
                    cls_of=lambda i, r: f"t{i % 8}")

    shared = {r["contributor"] for r in activity} & {r["contributor"] for r in heat}
    y = 100 + 8 * 22 + 26
    parts.append(text(66, y, f"{len(shared)} of the top 8 appear in both lists, and not in the same order.", "ink", 12))
    parts.append(text(66, y + 18, "Activity counts decays; decay heat counts the joules each decay releases, and a nuclide can be prolific and gentle or", "muted", 11.5))
    parts.append(text(66, y + 34, "rare and violent. Neither ranking is more correct — they answer different questions, and the metric is the question.", "muted", 11.5))
    parts.append(text(66, y + 56, "Both are geometry-free: they are properties of the material, so they can be compared before anyone has chosen a place to stand.", "muted", 11.5))
    write(path, w, y + 76, parts, "The same inventory ranked by two metrics")
    print(f"  rank: {len(shared)} contributors shared between the two top-8 lists")


def figure_spectrum(path):
    """Which photon lines carry the emission, which is what a detector actually sees."""
    rows = read_csv("scenario-spectrum.csv")

    def line_energy(row):
        # The contributor label for a line aggregate is "<nuclide> <energy> keV"; the energy is
        # what orders the spectrum, so it is parsed rather than assumed to be the rank order.
        for token in row["contributor"].replace("keV", "").split():
            try:
                return float(token)
            except ValueError:
                continue
        return 0.0

    rows = sorted(rows, key=line_energy)
    energies = [line_energy(r) for r in rows]
    values = [float(r["value"]) for r in rows]

    w, h = 900, 470
    ax = Axes(84, 820, 84, 300, (0, max(energies) * 1.08), (0, max(values) * 1.25))
    parts = []
    grid = [max(values) * f for f in (0.25, 0.5, 0.75, 1.0)]
    parts += ax.hgrid(grid, [si(g) for g in grid])
    ticks = [t for t in (0, 250, 500, 750, 1000, 1250, 1500, 2000, 2500) if t <= max(energies) * 1.08]
    parts += ax.vgrid(ticks, [f"{t:g}" for t in ticks])

    for i, (energy, value) in enumerate(zip(energies, values)):
        x = ax.x(energy)
        parts.append(line(x, ax.bottom, x, ax.y(value), f"s{i % 8}", 2.4))
        parts.append(circle(x, ax.y(value), 2.6, f"t{i % 8}"))
    # Only the strongest few are labeled: a spectrum with fourteen labels is a spectrum nobody
    # can read, and the ones that matter are the ones a detector will resolve first.
    for row, energy, value in sorted(zip(rows, energies, values), key=lambda z: -z[2])[:5]:
        parts.append(text(ax.x(energy), ax.y(value) - 9, row["contributor"], "ink", 10, "middle", "600"))
    parts += ax.frame()

    header(parts, ax, "Photon emission line by line, 1 day after fission",
           "`nusift spectrum --by line --metric photon` — photons per second, 20 kt U-235 thermal")
    parts.append(text(ax.right, ax.bottom + 34, "photon energy (keV) →", "muted", 11, "end"))
    notes(parts, ax, [
        "This is the ranking a gamma spectrometer sees, and it is not the nuclide ranking: one nuclide can hold several lines and a",
        "line is not owned by the nuclide with the most activity. Ranking by line is why 'which peak am I looking at' is a question the",
        "tool can answer directly, rather than one the reader has to reconstruct from a nuclide list and a table of intensities.",
    ])
    write(path, w, h, parts, "Photon line spectrum one day after fission")
    print(f"  spectrum: {len(rows)} lines, {min(energies):.0f}-{max(energies):.0f} keV")


def figure_forecast(path):
    """Who leads, and over which stretch of time."""
    windows = read_csv("scenario-forecast.csv")
    w = 900
    left, top = 74, 100
    span_lo = min(float(win["start_s"]) for win in windows)
    span_hi = max(float(win["end_s"]) for win in windows)

    ax = Axes(left, 820, top, top + 120, (span_lo, span_hi), (0.0, 1.0), xlog=True)
    parts = []
    parts += time_axis(ax, span_lo, span_hi)
    for i, win in enumerate(windows):
        x0, x1 = ax.x(float(win["start_s"])), ax.x(float(win["end_s"]))
        parts.append(rect(x0, top, x1 - x0, 120, f"t{i % 8}", 0.20, rx=2, width=0))
        parts.append(line(x0, top, x0, top + 120, "axis", 0.9, "2 4"))
        row = i % 3
        parts.append(text((x0 + x1) / 2, top + 26 + row * 34, win["label"], f"t{i % 8}", 10.5, "middle", "600"))
        parts.append(text((x0 + x1) / 2, top + 39 + row * 34,
                          f"{float(win['peak_fraction']) * 100:.0f}%", "muted", 9.5, "middle"))
    parts.append(rect(ax.x(span_lo), top, ax.x(span_hi) - ax.x(span_lo), 120, "box", 0, rx=2))
    parts += ax.frame()

    header(parts, ax, "Who leads the activity, and until when",
           "`nusift forecast` — 20 kt U-235 thermal fission, 1 minute to 100 years")
    parts.append(text(ax.left, top + 152, "time after fission →", "muted", 11))
    y = notes(parts, ax, [
        f"{len(windows)} leadership changes across the window, each with the share the leader holds at its peak.",
        "A boundary is a located crossing rather than a sample time: two contributors' curves cross somewhere between two grid points,",
        "and the forecast reports where, not which sample happened to be nearest. The same machinery locates every event in `when`,",
        "so a dominance boundary and a threshold crossing cannot disagree about the same instant.",
    ], top=top + 180)
    write(path, w, y + 24, parts, "Dominance windows over a century")
    print(f"  forecast: {len(windows)} windows")


def figure_when(path):
    """A located event, with the bracket it was found in."""
    events = read_csv("scenario-when.csv")
    crossing = next(e for e in events if e["kind"] == "falling")
    t = float(crossing["time_s"])
    b0, b1 = float(crossing["bracket_start_s"]), float(crossing["bracket_end_s"])
    level = float(crossing["value"])
    located = float(crossing["located_to_s"])

    w, h = 900, 460
    ax = Axes(84, 820, 92, 300, (b0 * 0.45, b1 * 2.2), (level * 0.45, level * 2.4), xlog=True, ylog=True)
    parts = []
    parts += ax.hgrid([level * 0.5, level, level * 2], ["500 W", "1 kW", "2 kW"])
    ticks = [v for v in (86400 * 200, 86400 * 300, 86400 * 400, 86400 * 600) if b0 * 0.45 <= v <= b1 * 2.2]
    parts += ax.vgrid(ticks, [duration(v) for v in ticks])

    # The bracket the grid actually observed, and the point inside it the refinement found.
    parts.append(rect(ax.x(b0), ax.top, ax.x(b1) - ax.x(b0), ax.bottom - ax.top, "band", 0.12, rx=2, width=0))
    parts.append(line(ax.x(b0), ax.top, ax.x(b0), ax.bottom, "accent", 1.2, "3 3"))
    parts.append(line(ax.x(b1), ax.top, ax.x(b1), ax.bottom, "accent", 1.2, "3 3"))
    parts.append(line(ax.left, ax.y(level), ax.right, ax.y(level), "axis", 1.4, "6 4"))
    parts.append(line(ax.x(t), ax.top, ax.x(t), ax.bottom, "s0", 2.0))
    parts.append(circle(ax.x(t), ax.y(level), 4.0, "fill-a"))
    parts.append(text(ax.x(t), ax.top - 10, duration(t), "t0", 11.5, "middle", "600"))
    parts.append(text(ax.x(b0), ax.bottom + 16, duration(b0), "warn", 10, "middle"))
    parts.append(text(ax.x(b1), ax.bottom + 16, duration(b1), "warn", 10, "middle"))
    parts.append(text((ax.x(b0) + ax.x(b1)) / 2, ax.top + 18, "the bracket the grid observed", "warn", 10.5, "middle"))
    parts += ax.frame()

    header(parts, ax, "When does the debris fall below a kilowatt of decay heat?",
           "`nusift when --metric heat --level 1000 --refine` — 20 kt U-235 thermal fission")
    y = notes(parts, ax, [
        f"The grid bracketed the crossing between {duration(b0)} and {duration(b1)}; refinement located it at {duration(t)}, to within {located:.2g} s.",
        "The bracket is reported, not hidden. An event the grid never straddled is not found at all, and one located between two samples",
        "is narrowed by re-solving inside the bracket rather than by interpolating across it — `refined` says which of the two happened.",
        "Decay heat needs no geometry, so this date is a property of the material rather than of where anyone is standing.",
    ], top=ax.bottom + 44)
    write(path, w, y + 24, parts, "A located threshold crossing with its bracket")
    print(f"  when: crossing at {duration(t)}, bracket {duration(b0)}-{duration(b1)}")


def figure_shortlist(path):
    """The smallest set that holds a coverage floor everywhere, and what each member adds."""
    rows = read_csv("scenario-shortlist.csv")
    members = [r for r in rows if r["kind"] == "member"]
    binding = [r for r in rows if r["kind"] == "binding"]

    w = 900
    parts = []
    parts.append(text(74, 26, "The smallest monitoring list that holds 95% of two metrics at every time", "ink", 13, "start", "600"))
    parts.append(text(74, 44, "`nusift shortlist --metrics activity,heat --coverage 0.95` — 20 kt fission, 1 h to 100 y", "muted", 11.5))

    shown = members[:14]
    ranked_bars(parts, 74, 84, 760, shown,
                value_of=lambda r: float(r["peak_fraction"]),
                label_of=lambda r: r["contributor"],
                note_of=lambda r: f"peak share {float(r['peak_fraction']) * 100:.1f}%",
                cls_of=lambda i, r: "fill-a")

    y = 84 + len(shown) * 22 + 24
    tight = binding[0] if binding else None
    parts.append(text(74, y, f"{len(members)} nuclides hold 95% of both metrics at every one of the 40 times — 80 constraints in all.", "ink", 12))
    if tight is not None:
        parts.append(text(74, y + 20,
                          f"The tightest is {tight['requirement']} at {duration(number(tight, 'time_s'))}, where the set achieves "
                          f"{number(tight, 'achieved') * 100:.2f}% against the {number(tight, 'required') * 100:.0f}% floor — the margin the whole "
                          "set is sized by.", "muted", 11.5))
    parts.append(text(74, y + 40, "The ORDER is not a ranking. Each member is whichever most improved the constraints still unmet given the ones before it,", "muted", 11.5))
    parts.append(text(74, y + 56, "so the second entry is not the second largest contributor — it is the one that covered what the first left uncovered.", "muted", 11.5))
    parts.append(text(74, y + 78, "Nor is this the smallest such set. Greedy cover is not exact, and the report says so rather than letting a numbered list", "muted", 11.5))
    parts.append(text(74, y + 94, "be read as a proof of minimality.", "muted", 11.5))
    if len(members) > len(shown):
        parts.append(text(74, y + 116, f"Showing the first {len(shown)} of {len(members)}.", "muted", 11))
    write(path, w, y + 136, parts, "A robust triage set over two metrics")
    print(f"  shortlist: {len(members)} members, tightest {binding[0]['requirement'] if binding else '?'}")


def figure_source(path):
    """The binned photon source a transport code wants."""
    every = read_csv("scenario-source.csv")
    # The deck's last rows are the under-range, over-range and total lines rather than bins, and
    # they carry no energy pair. Kept in the file because a source term without them is missing
    # the part that says what fell outside the binning; dropped here because they are not bars.
    rows = [r for r in every if r["bin"].isdigit()]
    summary = {r["bin"]: r for r in every if not r["bin"].isdigit()}
    lo = [float(r["energy_low_ev"]) / 1000.0 for r in rows]
    hi = [float(r["energy_high_ev"]) / 1000.0 for r in rows]
    value = [float(r["emission"]) for r in rows]

    w, h = 900, 460
    top = max(value)
    ax = Axes(84, 820, 88, 300, (0, max(hi)), (0, top * 1.18))
    parts = []
    grid = [top * f for f in (0.25, 0.5, 0.75, 1.0)]
    parts += ax.hgrid(grid, [si(g) for g in grid])
    ticks = [t for t in (0, 500, 1000, 1500, 2000, 2500, 3000) if t <= max(hi)]
    parts += ax.vgrid(ticks, [f"{t:g}" for t in ticks])

    for a, b, v in zip(lo, hi, value):
        if v <= 0:
            continue
        x0, x1 = ax.x(a), ax.x(b)
        parts.append(rect(x0, ax.y(v), max(x1 - x0 - 0.7, 0.8), ax.bottom - ax.y(v), "fill-a", 0.7, rx=0, width=0))
    parts += ax.frame()

    header(parts, ax, "The same photons, binned as a transport code's source definition",
           "`nusift source --bins 40` — writes MCNP SDEF or an OpenMC source, 20 kt fission at 1 day")
    parts.append(text(ax.right, ax.bottom + 34, "photon energy (keV) →", "muted", 11, "end"))
    notes(parts, ax, [
        "This is the handoff. NuSIFT deliberately does not do shielding, so the useful thing it can do for a transport code is hand it a",
        "source term with the provenance still attached — which evaluation, which seed, which cooling time.",
        "Binning is lossy and the deck says so: a line spectrum forced into 40 bins is an approximation the receiving code cannot detect,",
        "so what was approximated is written into the deck as a comment rather than left for someone to rediscover — including how much",
        "emission fell below the first bin and above the last, which are rows in the output rather than silent losses.",
    ])
    write(path, w, h, parts, "Binned photon source term")
    print(f"  source: {len(rows)} bins to {max(hi):.0f} keV")


def figure_attribute(path):
    """Which seeded nuclide the answer is riding on, which is not who is emitting."""
    rows = read_csv("scenario-attribute.csv")[:9]
    w = 900
    parts = []
    parts.append(text(74, 26, "Which seeded nuclide is the 30-day activity actually riding on?", "ink", 13, "start", "600"))
    parts.append(text(74, 44, "`nusift attribute` — one adjoint solve, 20 kt U-235 thermal fission", "muted", 11.5))

    ranked_bars(parts, 74, 88, 760, rows,
                value_of=lambda r: float(r["fraction"]),
                label_of=lambda r: r["seed"],
                note_of=lambda r: f"{float(r['fraction']) * 100:.1f}% of the answer",
                cls_of=lambda i, r: "fill-a")

    y = 88 + len(rows) * 22 + 24
    parts.append(text(74, y, "A share here is exact, not apportioned: the response is linear in the seed, so the shares partition it and sum to one.", "ink", 12))
    parts.append(text(74, y + 20, "This is the reverse of a ranking. A ranking says which nuclide is emitting at 30 days; this says which nuclide PRESENT AT ZERO", "muted", 11.5))
    parts.append(text(74, y + 36, "is responsible for it — and for a chain those are different nuclides, because the emitter was grown in by something else.", "muted", 11.5))
    parts.append(text(74, y + 58, "It costs one adjoint solve for the whole partition, where asking the same question by re-running the forward solve once per", "muted", 11.5))
    parts.append(text(74, y + 74, "seeded nuclide would cost a thousand.", "muted", 11.5))
    write(path, w, y + 94, parts, "Seed attribution from one adjoint solve")
    print(f"  attribute: top seed {rows[0]['seed']} at {float(rows[0]['fraction']) * 100:.1f}%")


# ======================================================================================
# Track 2 -- working around a compact source
# ======================================================================================

def figure_rank_component(path):
    """What sets the field around the object someone has to work on."""
    rows = read_csv("scenario-rank-component.csv")
    w = 900
    parts = []
    parts.append(text(74, 26, "What sets the field around the component, five years on", "ink", 13, "start", "600"))
    parts.append(text(74, 44, "`nusift rank --metric exposure --units Sv/h --distance 2` — examples/contaminated_component.csv", "muted", 11.5))

    ranked_bars(parts, 74, 88, 760, rows,
                value_of=lambda r: float(r["value"]),
                label_of=lambda r: r["contributor"],
                note_of=lambda r: f"{si(float(r['value']))} Sv/h   {float(r['fraction']) * 100:.1f}%",
                cls_of=lambda i, r: "fill-a")

    y = 88 + len(rows) * 22 + 24
    parts.append(text(74, y, "Sr-90 and Y-90 carry more activity than anything else in this object and are nowhere in this list.", "ink", 12))
    parts.append(text(74, y + 20, "They are beta emitters: a curie of Sr-90 and a curie of Cs-137 are the same number of decays per second and nothing like", "muted", 11.5))
    parts.append(text(74, y + 36, "the same hazard at two meters. Which is the point of having metrics at all — the inventory did not change, the question did.", "muted", 11.5))
    parts.append(text(74, y + 58, "A point source at 2 m is the model here, and it fits: the object is compact. The same kernel pointed at a contaminated field", "muted", 11.5))
    parts.append(text(74, y + 74, "would not be, which is why the fission-debris figures above are all in quantities that need no geometry.", "muted", 11.5))
    write(path, w, y + 94, parts, "Exposure ranking around a compact source")
    print(f"  component: {rows[0]['contributor']} leads at {float(rows[0]['fraction']) * 100:.1f}%")


def figure_stay(path):
    """How long a person may stay, against when they go in."""
    rows = read_csv("scenario-stay.csv")
    starts = [float(r["start_s"]) for r in rows]
    durations = [float(r["duration_s"]) for r in rows]
    budget = float(rows[0]["budget"])

    w, h = 900, 470
    ax = Axes(84, 800, 92, 320, (starts[0] * 0.7, starts[-1] * 1.5),
              (min(durations) * 0.7, max(durations) * 1.5), xlog=True, ylog=True)
    parts = []
    minutes = [60, 300, 900, 1800, 3600, 7200]
    keep = [m for m in minutes if min(durations) * 0.7 <= m <= max(durations) * 1.5]
    parts += ax.hgrid(keep, [duration(m) for m in keep])
    parts += time_axis(ax, starts[0] * 0.7, starts[-1] * 1.5)
    parts.append(ax.path(starts, durations, "s0", 2.2))
    for x, y in zip(starts, durations):
        parts.append(circle(ax.x(x), ax.y(y), 3.0, "fill-a"))
    parts.append(text(ax.x(starts[0]), ax.y(durations[0]) - 10, duration(durations[0]), "t0", 10.5, "middle", "600"))
    parts.append(text(ax.x(starts[-1]), ax.y(durations[-1]) - 10, duration(durations[-1]), "t0", 10.5, "middle", "600"))
    parts += ax.frame()

    header(parts, ax, f"How long may someone stay, on a {budget * 1000:.0f} mSv budget at 2 m?",
           "`nusift stay` — examples/contaminated_component.csv, against when the job starts")
    parts.append(text(ax.right, ax.bottom + 34, "when the job starts →", "muted", 11, "end"))
    notes(parts, ax, [
        f"Waiting from {duration(starts[0])} to {duration(starts[-1])} buys a factor of {max(durations) / min(durations):.1f} in permitted stay.",
        "That factor is the number a scheduling argument actually needs, and a dose rate is not it.",
        "This is the interval integral inverted. The accrued dose over a stay is exact in closed form, so what is approximated is only",
        "where the root sits, and the report states the tolerance it was located to. A budget not spent inside the maximum stay is",
        "reported as not spent, rather than as an implausibly long duration nobody would have believed anyway.",
    ])
    write(path, w, h, parts, "Permitted stay time against entry time")
    print(f"  stay: {duration(durations[0])} at {duration(starts[0])} to {duration(durations[-1])} at {duration(starts[-1])}")


def figure_plan(path):
    """A job with a shape: legs at their own distances, against the budget."""
    rows = read_csv("scenario-plan.csv")
    budget = 0.02
    total = float(rows[-1]["cumulative"])

    w = 900
    left, top = 74, 100
    bar_w = 620
    parts = []
    parts.append(text(left, 26, "What the job costs, leg by leg", "ink", 13, "start", "600"))
    parts.append(text(left, 44, "`nusift plan --budget 0.02` — five years on, examples/contaminated_component.csv", "muted", 11.5))

    span = max(float(r["accrued"]) for r in rows) or 1.0
    for i, row in enumerate(rows):
        y = top + i * 34
        is_break = row["is_break"] == "true"
        cls = "muted" if is_break else f"t{i % 8}"
        parts.append(text(left, y + 12, row["leg"], "ink", 11.5, "start", "500"))
        length = bar_w * float(row["accrued"]) / span
        parts.append(rect(left + 128, y, max(length, 1.0), 14, "box" if is_break else cls, 0.0 if is_break else 0.75, rx=2, width=1.0 if is_break else 0))
        detail = "no dose — and it still takes ten minutes of the day" if is_break else (
            f"{si(float(row['accrued']))} Sv   {float(row['fraction']) * 100:.1f}% of the total"
            + (f"   at {row['distance_m']} m" if row["distance_m"] else ""))
        # Under the bar rather than after it: the longest bar is nearly the full width, so a
        # trailing label would run off the canvas on exactly the leg that matters most.
        parts.append(text(left + 128, y + 27, detail, "muted", 10.5))

    y = top + len(rows) * 34 + 10
    parts.append(line(left + 128, y, left + 128 + bar_w, y, "axis", 1.0))
    y += 22
    # Where the budget runs out, from the cumulative column and the leg's own mean rate -- the
    # same arithmetic the report prints, done here so the figure cannot claim a different leg.
    spent_in, spent_at = None, 0.0
    for row in rows:
        if number(row, "cumulative") >= budget:
            before = number(row, "cumulative") - number(row, "accrued")
            rate = number(row, "mean_rate_per_s")
            spent_in = row["leg"]
            spent_at = (budget - before) / rate if rate > 0 else 0.0
            break
    if spent_in is None:
        parts.append(text(left, y, f"Total {si(total)} Sv, inside a budget of {si(budget)} Sv.", "ink", 12))
    else:
        parts.append(text(left, y, f"The budget of {si(budget)} Sv is spent {duration(spent_at)} into \"{spent_in}\" — the plan as written accrues {total / budget * 100:.0f}% of it.", "ink", 12))
    parts.append(text(left, y + 20, "The mean-rate column is what makes breaking a job into legs worth doing: two legs with the same dose are different problems", "muted", 11.5))
    parts.append(text(left, y + 36, "when one is fifteen minutes at two meters and the other is forty-five at one, and only the rate separates them.", "muted", 11.5))
    parts.append(text(left, y + 58, "Naming the leg and the minute is the point. A plan that simply reports 'over budget' leaves the reader to work out which part", "muted", 11.5))
    parts.append(text(left, y + 74, "to shorten, move further out, or share between two people — and those are the only three things anyone can actually do.", "muted", 11.5))
    parts.append(text(left, y + 96, "A break carries no dose and still carries time, so the legs after it start later against a source that has decayed further.", "muted", 11.5))
    parts.append(text(left, y + 112, "That is why a break is spelled as a leg rather than subtracted afterwards: it keeps its place in the sequence.", "muted", 11.5))
    write(path, w, y + 132, parts, "A job costed leg by leg against a dose budget")
    print(f"  plan: {len(rows)} legs, {si(total)} Sv total")


def figure_intervene(path):
    """What taking something out is worth, in the tool's own currency."""
    rows = read_csv("scenario-intervene.csv")
    # One row per intervention; the per-nuclide rows repeat the intervention total.
    seen = {}
    for row in rows:
        seen.setdefault(row["intervention"], row)
    options = list(seen.values())
    base = float(options[0]["response"]) + float(options[0]["removed"])

    w = 900
    left, top = 74, 108
    parts = []
    parts.append(text(left, 26, "What is a separation actually worth?", "ink", 13, "start", "600"))
    parts.append(text(left, 44, "`nusift intervene --remove Cs --remove Co --remove Eu` — dose rate at 2 m, thirty years on", "muted", 11.5))
    parts.append(text(left, 84, f"leave it alone: {si(base)} Sv/h", "muted", 11))

    bar_w = 430
    for i, row in enumerate(options):
        y = top + i * 40
        remaining = float(row["response"])
        parts.append(text(left, y + 12, f"remove {row['intervention']}", "ink", 11.5, "start", "500"))
        parts.append(rect(left + 128, y, bar_w, 14, "box", 0.0, rx=2, width=1.0))
        parts.append(rect(left + 128, y, bar_w * remaining / base, 14, f"t{i % 8}", 0.8, rx=2, width=0))
        parts.append(text(left + 128 + bar_w + 10, y + 12,
                          f"{si(remaining)} Sv/h left — {float(row['removed_fraction']) * 100:.1f}% removed",
                          "muted", 10.5))

    y = top + len(options) * 40 + 16
    best = max(options, key=lambda r: float(r["removed_fraction"]))
    parts.append(text(left, y, f"Removing {best['intervention']} takes {float(best['removed_fraction']) * 100:.1f}% of the field with it; the other two are worth about a percent between them.", "ink", 12))
    parts.append(text(left, y + 20, "The answer is exact and costs one adjoint solve per option, because the response is linear in what is left behind.", "muted", 11.5))
    parts.append(text(left, y + 36, "It is a counterfactual on the SEED: remove this much of this element on this date, then ask the later question again.", "muted", 11.5))
    parts.append(text(left, y + 58, "Which is how 'is a cesium separation worth doing before storage' becomes a number rather than an argument — in the same", "muted", 11.5))
    parts.append(text(left, y + 74, "units as the dose limit it is being weighed against.", "muted", 11.5))
    write(path, w, y + 94, parts, "The value of a separation, priced in dose rate")
    print(f"  intervene: {len(options)} options, best {best['intervention']}")


def figure_sensitivity(path):
    """How much the answer rests on evaluated half-lives, and where the terms cancel."""
    rows = read_csv("scenario-sensitivity.csv")
    ranked = sorted(rows, key=lambda r: -abs(number(r, "elasticity")))[:10]

    w = 900
    parts = []
    parts.append(text(74, 26, "How much does this answer rest on the evaluated half-lives?", "ink", 13, "start", "600"))
    parts.append(text(74, 44, "`nusift sensitivity` — elasticity of the 30-year dose rate to each nuclide's decay constant", "muted", 11.5))

    ranked_bars(parts, 74, 88, 740, ranked,
                value_of=lambda r: abs(number(r, "elasticity")),
                label_of=lambda r: r["nuclide"],
                note_of=lambda r: (f"{number(r, 'elasticity'):+.3g}"
                                   + (f"   x {number(r, 'relative_uncertainty') * 100:.2g}% sigma"
                                      if number(r, "relative_uncertainty") > 0 else "   no sigma evaluated")),
                cls_of=lambda i, r: "fill-a")

    y = 88 + len(ranked) * 22 + 24
    withsigma = sum(1 for r in rows if number(r, "relative_uncertainty") > 0)
    parts.append(text(74, y, "The elasticity leads, not the derivative, and the reason is cancellation.", "ink", 12))
    parts.append(text(74, y + 20, "At secular equilibrium a daughter's activity is pinned by its parent's feed rate, so moving the daughter's own half-life barely", "muted", 11.5))
    parts.append(text(74, y + 36, "moves the answer: two large terms annihilate across several digits and a relative error against their difference means nothing.", "muted", 11.5))
    parts.append(text(74, y + 58, "A fractional response to a fractional perturbation survives that, and multiplies a relative sigma directly.", "muted", 11.5))
    parts.append(text(74, y + 80, f"{withsigma} of {len(rows)} nuclides here carry an evaluated uncertainty. The rest contribute a sensitivity with no error bar to", "muted", 11.5))
    parts.append(text(74, y + 96, "attach to it, which the report counts rather than quietly treating as zero.", "muted", 11.5))
    write(path, w, y + 116, parts, "Half-life sensitivity of a dose-rate answer")
    print(f"  sensitivity: {len(rows)} nuclides, {withsigma} with an evaluated sigma")


# ======================================================================================
# Track 3 -- waste, transport and disposal
# ======================================================================================

def figure_allowable(path):
    """How much of this could be shipped, and how that changes as it decays."""
    rows = read_csv("scenario-allowable.csv")
    times = [float(r["time_s"]) for r in rows]
    scale = [float(r["allowed_scale"]) for r in rows]

    w, h = 900, 470
    ax = Axes(84, 800, 92, 320, (times[0], times[-1]), (min(scale) * 0.7, max(scale) * 1.6),
              xlog=True, ylog=True)
    parts = []
    exponent = int(math.floor(math.log10(min(scale) * 0.7)))
    grid = [10.0**e for e in range(exponent, exponent + 4)]
    parts += ax.hgrid(grid, [f"1e{e}" for e in range(exponent, exponent + 4)])
    parts += time_axis(ax, times[0], times[-1])
    parts.append(line(ax.left, ax.y(1.0), ax.right, ax.y(1.0), "accent", 1.4, "6 4") if min(scale) * 0.7 <= 1.0 <= max(scale) * 1.6 else "")
    parts.append(ax.path(times, scale, "s0", 2.2))
    parts += ax.frame()

    header(parts, ax, "By what factor could this be scaled before the transport index binds?",
           "`nusift allowable --pack iaea-ssr6-a2.csv --limit 1.0` — the component, over a thousand years")
    parts.append(text(ax.right, ax.bottom + 34, "time →", "muted", 11, "end"))
    notes(parts, ax, [
        f"At one year the allowed scale is {si(scale[0])}: this object is about {si(1 / scale[0])} times over a single package's A2 sum of fractions.",
        "The curve is how much could be held, shipped or released as it decays, and the limiting nuclide can change along it — which is",
        "the thing a single number at a single date cannot tell anyone.",
        "It is a SCREENING INDEX and not a classification. The sum of fractions is the linear core of the rule; the rule around it —",
        "special form, fissile status, package type — is not a weighted sum and does not live in this layer.",
    ])
    write(path, w, h, parts, "Maximum allowable scale against time")
    print(f"  allowable: {si(scale[0])} at 1 y to {si(scale[-1])} at 1000 y")


def figure_uncertainty(path):
    """Which measurement to improve, which is not which nuclide dominates."""
    rows = read_csv("scenario-uncertainty.csv")
    w = 900
    left, top = 74, 108
    bar_w = 300
    parts = []
    parts.append(text(left, 26, "Which measurement should be improved?", "ink", 13, "start", "600"))
    parts.append(text(left, 44, "`nusift uncertainty` — three assays on three dates, dose rate at 2 m five years on", "muted", 11.5))
    parts.append(text(left + 150, 88, "share of the answer", "muted", 10.5, "middle"))
    parts.append(text(left + 150 + bar_w + 60, 88, "share of the variance", "muted", 10.5, "middle"))

    for i, row in enumerate(rows):
        y = top + i * 26
        share = float(row["share"])
        variance = float(row["variance_fraction"])
        total_share = sum(float(r["share"]) for r in rows)
        parts.append(text(left, y + 11, row["seed"], "ink", 11, "start", "500"))
        # Two bars growing from a common center line, so a row that is large in one and
        # negligible in the other is visible as an asymmetry rather than as two numbers.
        s = bar_w * (share / total_share)
        v = bar_w * variance
        parts.append(rect(left + 150 + bar_w - s, y, max(s, 0.8), 13, "fill-a", 0.75, rx=1.5, width=0))
        parts.append(rect(left + 150 + bar_w + 60, y, max(v, 0.8), 13, "fill-b", 0.75, rx=1.5, width=0))
        inside = s > 46
        parts.append(text(left + 150 + bar_w - s + (6 if inside else -8), y + 11,
                          f"{share / total_share * 100:.2g}%", "bg" if inside else "muted", 10,
                          "start" if inside else "end"))
        # Same treatment on the variance side: a row holding almost all of it has a bar that
        # reaches the margin, so its label goes inside rather than past the edge.
        v_inside = v > 46
        parts.append(text(left + 150 + bar_w + 60 + (v - 6 if v_inside else v + 8), y + 11,
                          f"{variance * 100:.2g}%", "bg" if v_inside else "muted", 10,
                          "end" if v_inside else "start"))

    y = top + len(rows) * 26 + 26
    parts.append(text(left, y, "These are different questions and they have different answers.", "ink", 12))
    parts.append(text(left, y + 20, "Sr-90 was assayed to 18% and contributes essentially nothing to this error bar, because it contributes essentially nothing", "muted", 11.5))
    parts.append(text(left, y + 36, "to a photon dose rate. Re-counting it more carefully would improve nothing. Cs-137, assayed to 3%, holds almost all of both.", "muted", 11.5))
    parts.append(text(left, y + 58, "The propagation is exact rather than first order: the response is linear in the seed, so there is no expansion and no", "muted", 11.5))
    parts.append(text(left, y + 74, "estimated derivative. What is assumed is the SHAPE of the covariance — a per-row sigma is its diagonal, which asserts the", "muted", 11.5))
    parts.append(text(left, y + 90, "assay errors are independent, and the report says so because nothing here can detect otherwise.", "muted", 11.5))
    write(path, w, y + 110, parts, "Assay uncertainty: share of the answer against share of the variance")
    print(f"  uncertainty: {len(rows)} rows")


def figure_reconcile(path):
    """Three sheets from three dates, brought to one -- and what appears that nobody measured."""
    rows = read_csv("scenario-reconcile.csv")
    sheets = [r for r in rows if r["kind"] == "assay"]
    merged = [r for r in rows if r["kind"] == "merged"]
    assayed = {"Cs-137", "Co-60", "Sr-90", "Eu-154", "Am-241", "Pu-239", "Pu-240"}
    grown = [r for r in merged if r["nuclide"] not in assayed]

    w = 900
    left = 74
    parts = []
    parts.append(text(left, 26, "Three assays, three dates, one inventory", "ink", 13, "start", "600"))
    parts.append(text(left, 44, "`nusift reconcile` — every sheet carried forward to the latest of them", "muted", 11.5))

    y = 88
    parts.append(text(left, y, "the sheets", "ink", 11.5, "start", "600"))
    y += 20
    for i, sheet in enumerate(sheets):
        carry = number(sheet, "carried_s")
        parts.append(text(left + 14, y + 11, sheet["assayed"], "ink", 11, "start", "500"))
        parts.append(text(left + 150, y + 11,
                          "already at the epoch" if carry <= 0 else f"carried forward {duration(carry)}",
                          f"t{i % 8}", 10.5))
        parts.append(text(left + 330, y + 11,
                          f"{si(number(sheet, 'atoms_at_assay'))} atoms on the sheet", "muted", 10.5))
        y += 20

    y += 18
    parts.append(text(left, y, f"what came out: {len(merged)} nuclides, of which {len(grown)} were on no sheet at all",
                      "ink", 11.5, "start", "600"))
    y += 20
    span = max(number(r, "atoms") for r in merged)
    for i, row in enumerate(sorted(merged, key=lambda r: -number(r, "atoms"))):
        atoms = number(row, "atoms")
        was_measured = row["nuclide"] in assayed
        parts.append(text(left + 14, y + 11, row["nuclide"], "ink" if was_measured else "warn", 11,
                          "start", "500" if was_measured else "600"))
        parts.append(rect(left + 110, y, max(560 * atoms / span, 0.8), 13,
                          "fill-a" if was_measured else "fill-b", 0.75, rx=1.5, width=0))
        parts.append(text(left + 110 + max(560 * atoms / span, 0.8) + 8, y + 11,
                          si(atoms) + ("" if was_measured else "   grown in"), "muted", 10))
        y += 17

    y += 22
    parts.append(text(left, y, "Ba-137m was on no sheet, and it is what sets the dose rate around this object.", "ink", 12))
    parts.append(text(left, y + 20, "That is the argument for reconciliation being a decay SOLVE per sheet rather than a per-nuclide exponential: a sheet lists", "muted", 11.5))
    parts.append(text(left, y + 36, "what was counted, and carrying it forward grows in everything the counted nuclides feed, whether or not anyone looked for it.", "muted", 11.5))
    parts.append(text(left, y + 58, "Every sheet is carried FORWARD and none backward, which is a refusal rather than a limitation. Un-growing a daughter is an", "muted", 11.5))
    parts.append(text(left, y + 74, "inverse problem with no unique answer, so an epoch earlier than an assay is rejected rather than answered with one of them.", "muted", 11.5))
    write(path, w, y + 94, parts, "Assays from several dates reconciled to one")
    print(f"  reconcile: {len(sheets)} sheets in, {len(merged)} nuclides out, {len(grown)} never measured")


def figure_integrate(path):
    """The rate at the end of a window, against the total accrued over it."""
    rate = read_csv("scenario-integrate-rate.csv")[:8]
    total = read_csv("scenario-integrate-total.csv")[:8]

    w = 900
    parts = []
    parts.append(text(66, 26, "What is happening now, and what happened over the decade", "ink", 13, "start", "600"))
    parts.append(text(66, 44, "20 kt U-235 thermal fission, decay heat — `nusift rank --at 10y` beside `nusift integrate --interval 0,10y`", "muted", 11.5))

    for column, (title, rows) in enumerate(
            [("the RATE at 10 years  (W)", rate), ("the TOTAL accrued, 0 to 10 years  (J)", total)]):
        left = 66 + column * 452
        parts.append(text(left, 84, title, "ink", 11.5, "start", "600"))
        ranked_bars(parts, left, 100, 400, rows,
                    value_of=lambda r: float(r["value"]),
                    label_of=lambda r: r["contributor"],
                    note_of=lambda r: f"{float(r['fraction']) * 100:.1f}%",
                    cls_of=lambda i, r: "fill-a" if column == 0 else "fill-b")

    names = lambda rows: {r["contributor"] for r in rows}
    shared = names(rate) & names(total)
    early = {duration(3600.0): names(read_csv("scenario-integrate-1h.csv")[:8]) & names(total),
             duration(86400.0): names(read_csv("scenario-integrate-1d.csv")[:8]) & names(total)}

    y = 100 + 8 * 22 + 26
    parts.append(text(66, y, f"At the endpoint the two lists share {len(shared)} of eight entries.", "ink", 12))
    parts.append(text(66, y + 20, "The total is carried by nuclides that were gone within days, and by ten years the heat is being made by something else", "muted", 11.5))
    parts.append(text(66, y + 36, "entirely. The overlap depends on WHERE inside the window the rate is measured, and it is not zero everywhere:", "muted", 11.5))
    for i, (when, overlap) in enumerate(early.items()):
        parts.append(text(90, y + 58 + i * 17,
                          f"at {when}: {len(overlap)} of eight shared" +
                          (f" — {', '.join(sorted(overlap))}" if overlap else ""), "muted", 11))
    parts.append(text(66, y + 100, "So the endpoint is the sharp case rather than the general one. What is general is that a rate at ONE instant cannot stand in", "muted", 11.5))
    parts.append(text(66, y + 116, "for a total over a window, which is why the interval is a separate path rather than a rate multiplied by a duration.", "muted", 11.5))
    parts.append(text(66, y + 138, "The integral is exact in closed form — the same augmented solve that produces the atoms produces the atom-seconds — so no", "muted", 11.5))
    parts.append(text(66, y + 154, "time grid is involved and a narrow late window is as trustworthy as a wide early one.", "muted", 11.5))
    write(path, w, y + 174, parts, "A rate and a total, ranked side by side")
    print(f"  integrate: endpoint shares {len(shared)}/8; " +
          ", ".join(f"{k} shares {len(v)}/8" for k, v in early.items()))


FIGURES = [
    ("scenario-store.svg", figure_store),
    ("scenario-nuclide.svg", figure_nuclide),
    ("scenario-inventory.svg", figure_inventory),
    ("scenario-decay.svg", figure_decay),
    ("scenario-rank.svg", figure_rank_two_metrics),
    ("scenario-spectrum.svg", figure_spectrum),
    ("scenario-forecast.svg", figure_forecast),
    ("scenario-when.svg", figure_when),
    ("scenario-shortlist.svg", figure_shortlist),
    ("scenario-source.svg", figure_source),
    ("scenario-attribute.svg", figure_attribute),
    ("scenario-rank-component.svg", figure_rank_component),
    ("scenario-stay.svg", figure_stay),
    ("scenario-plan.svg", figure_plan),
    ("scenario-intervene.svg", figure_intervene),
    ("scenario-sensitivity.svg", figure_sensitivity),
    ("scenario-allowable.svg", figure_allowable),
    ("scenario-uncertainty.svg", figure_uncertainty),
    ("scenario-reconcile.svg", figure_reconcile),
    ("scenario-integrate.svg", figure_integrate),
]


def main():
    print(f"writing {len(FIGURES)} scenario figures to {OUT}")
    for name, builder in FIGURES:
        builder(OUT / name)
    print("done")


if __name__ == "__main__":
    main()
